"""The card's AUTO block: what a build measures, written back next to the prose.

A card is the readable, months-later context for a part. Most of it is hand-authored,
and one fenced region is not: the facts that only come from actually building the thing.

Two rules make the block trustworthy. It is regenerated, never hand-edited, so it cannot
disagree with the geometry. And it carries no timestamp, so regenerating it on unchanged
geometry produces no diff, which is what makes `nurb card` safe to run at any time and a
stale card visible in `git diff`.

It deliberately does not repeat the parameters. Keyword defaults are the parameters and
the part file is readable text, so copying them here would be the parallel `PARAMS` dict
the contract forbids, one level removed. The block holds what you cannot get by reading
the source.
"""

import pathlib

from . import checks

# The block is found by MARK, not by the whole opening line. Matching the exact wording
# would mean that changing it once duplicates the block in every card already on disk,
# since the old opener would no longer be recognised as one.
MARK = "<!-- AUTO"
OPEN = f"{MARK}: regenerated by `nurb card`. Do not hand-edit. -->"
CLOSE = "<!-- /AUTO -->"

REQUIRED = ("## What it is", "## Design notes", "## Don't", "## Changelog")


def facts(shape, ctx=None, findings=None, variants=None):
    """The lines of an AUTO block, in reading order.

    Every line stays ASCII, which is what `checks.py` already does in its own messages.
    A card's hand-written prose is free to say mm² because a human wrote it once. A
    generated line cannot: written on a cp1252 machine, mm³ comes back as invalid UTF-8
    everywhere else, and then nothing can read the card at all.
    """
    ctx = ctx or checks.Context()
    box = shape.bounding_box()
    solids = len(shape.solids())
    size = (
        f"Size: {box.size.X:.2f} x {box.size.Y:.2f} x {box.size.Z:.2f} mm, "
        f"{shape.volume:.1f} mm3, {solids} solid{'s' if solids != 1 else ''}, "
        f"{len(shape.faces())} faces"
    )
    lines = [size]

    small = [f for f in shape.faces() if f.area < ctx.sliver_area]
    if small:
        lines.append(
            f"Slivers: {len(small)} under {ctx.sliver_area}mm2, "
            f"smallest {min(f.area for f in small):.3f}mm2, "
            f"{ctx.accepted.get('sliver', 0)} accepted"
        )

    reaching = checks.projection(shape, ctx)
    if reaching:
        reach, height, ratio = reaching
        lines.append(
            f"Projection: {reach:.1f}mm over a {height:.1f}mm back, "
            f"ratio {ratio:.2f} against a {ctx.projection_limit:.1f} limit"
        )

    lines.append(f"Checks: {_verdict(findings)}")

    # One line per variant, because a variant is a shipped configuration and a card that
    # only described the defaults would leave the other three quarters of a family
    # unrecorded. A variant that stops building shows up here as a diff.
    for name, built, its_ctx, its_findings in variants or []:
        box = built.bounding_box()
        solids = len(built.solids())
        small = [f for f in built.faces() if f.area < its_ctx.sliver_area]
        lines.append(
            f"Variant {name}: {box.size.X:.2f} x {box.size.Y:.2f} x {box.size.Z:.2f} mm, "
            f"{built.volume:.1f} mm3, {solids} solid{'s' if solids != 1 else ''}, "
            f"{len(built.faces())} faces, {len(small)} under {its_ctx.sliver_area}mm2, "
            f"{_verdict(its_findings)}"
        )
    return lines


def _verdict(findings):
    if findings is None:
        return "not run"
    if not findings:
        return "clean"
    counted = {}
    for f in findings:
        counted.setdefault(f.severity, []).append(f.rule)
    parts = [
        f"{len(rules)} {severity} ({', '.join(sorted(set(rules)))})"
        for severity, rules in sorted(counted.items())
    ]
    return f"{len(findings)} finding{'s' if len(findings) != 1 else ''}: " + ", ".join(parts)


def render(lines):
    return "\n".join([OPEN, *lines, CLOSE])


def graft(text, lines):
    """Put the block into a card, replacing any block already there.

    Inserted under the title when absent, so a hand-written card needs no placeholder
    and `nurb new` does not have to emit one.
    """
    block = render(lines)
    if MARK in text and CLOSE in text:
        head, rest = text.split(MARK, 1)
        return head + block + rest.split(CLOSE, 1)[1]
    body = text.lstrip("\n")
    if body.startswith("# "):
        title, _, rest = body.partition("\n")
        rest = rest.lstrip("\n")
        return f"{title}\n\n{block}\n\n{rest}" if rest else f"{title}\n\n{block}\n"
    return f"{block}\n\n{body}"


def thin(text):
    """Required sections that are missing or have nothing under them.

    `## Don't` is the one that matters and the one most likely to be left empty. It is
    the only place that records what was tried and rejected, and without it the next
    agent helpfully re-adds the chamfer that was deliberately retired.
    """
    out = []
    for heading in REQUIRED:
        if heading not in text:
            out.append(heading)
            continue
        after = text.split(heading, 1)[1]
        body = after.split("\n## ", 1)[0]
        if not body.strip():
            out.append(heading)
    return out


def write(part_path, shape, ctx=None, findings=None, variants=None):
    """Regenerate a part's AUTO block. Returns (card_path, changed, thin_sections)."""
    card = pathlib.Path(part_path).with_suffix(".md")
    # Explicit utf-8 both ways. A card's prose says mm², so the locale default would read
    # it wrong on a machine that is not utf-8 and write back something nothing can read.
    was = card.read_text(encoding="utf-8") if card.is_file() else f"# {card.stem}\n"
    now = graft(was, facts(shape, ctx, findings, variants))
    if now != was:
        card.write_text(now, encoding="utf-8")
    return card, now != was, thin(now)
